### PR TITLE
Fixed issue #711

### PR DESCRIPTION
**Pull request by cool-raju**
Fixed issue #711 
responsive tabs issue fixed

### CODE REVIEW

**Comment by abiarnoldmichael** [comment]
Hi, this fix doesn't seem to work and instead seems to delete the arrows.

**Comment by cool-raju** [comment]
@abiarnoldmichael 
Hi yes, we have deleted the arrows. Because previously we have used the very older version of bootstrap. So tabs structure was different. With the new version, this is not supported. The main thing is to do this responsive. So please check this version. We have responsive these tabs with another way( which is compatible with the latest bootstrap )

**Comment by abiarnoldmichael** [comment]
Hi, we have used this fix. It does not work on mobile. When selecting a tab, the page reverts to the top of the screen so regardless of the arrows being there or not, it still doesn't navigate.

**Comment by cool-raju** [comment]
Hi @abiarnoldmichael 
After your comment, we have check multiple times. Its works perfectly.
localhost_wordpress_raj2_wcmp-vendor_khala-hbe-onek_699_ (1)
And whenever switch to other tabs it's working perfectly. Please check again.

**Comment by abiarnoldmichael** [comment]
https://user-images.githubusercontent.com/77331373/109963508-655e5200-7ce4-11eb-8713-22ca13d2a2e1.MP4
 When we click on these tabs, the screen moves to the top of the page. The tabs do not change.

**Comment by cool-raju** [comment]
Hi @abiarnoldmichael 
It might have your theme or plugin conflict. Can you please check with the default theme like twenty seventeen and plugins woocommerce and wcmp only

**Comment by abiarnoldmichael** [comment]
Thank you, yes it seems to be a theme conflict. Is there any way I can fix this? My site was working before this.

**Pull request closed without merging**
